# Generated by Django 4.0.4 on 2022-05-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_accomodations_created_at_accomodations_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=15),
        ),
    ]
