# Generated by Django 4.0.4 on 2022-05-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_alter_user_gallery_options'),
        ('colleges', '0002_book_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_industry',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='industry.registration'),
            preserve_default=False,
        ),
    ]
