# Generated by Django 4.0.4 on 2022-05-30 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_book_industry_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('colleges_user_id', models.IntegerField(default=0)),
                ('industry_user_id', models.IntegerField(default=0)),
                ('messages_text', models.TextField(default='null')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('colleges', 'Colleges'), ('industry', 'Industry')], default='colleges', max_length=15)),
                ('industry_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.book_industry')),
            ],
        ),
    ]
