# Generated by Django 4.0.4 on 2022-05-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_alter_user_gallery_options'),
        ('colleges', '0005_upload_resume_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_resume',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.registration'),
        ),
        migrations.AddField(
            model_name='upload_resume',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='industry.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_resume',
            name='industry_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.book_industry'),
        ),
    ]
