# Generated by Django 4.0.4 on 2022-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_upload_resume_college_upload_resume_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_resume',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
