# Generated by Django 4.0.4 on 2022-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_alter_book_industry_industry_response_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_industry',
            name='industry_response_letter',
            field=models.CharField(default='', max_length=3024, null=True),
        ),
        migrations.AlterField(
            model_name='book_industry',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted')], default='requested', max_length=15),
        ),
    ]
