# Generated by Django 4.0.1 on 2022-05-10 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(default='null', max_length=255)),
                ('website', models.CharField(default='null', max_length=500)),
                ('land_phone', models.CharField(default='null', max_length=15)),
                ('mobile_number', models.CharField(default='null', max_length=15)),
                ('email', models.CharField(default='null', max_length=255)),
                ('password', models.CharField(default='null', max_length=500)),
                ('pincode', models.IntegerField(default='null', max_length=10)),
                ('state', models.CharField(default='null', max_length=10)),
                ('address', models.CharField(default='null', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
