# Generated by Django 4.0.1 on 2022-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
