# Generated by Django 4.0.1 on 2022-05-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_remove_registration_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry.registration')),
            ],
        ),
    ]
