# Generated by Django 4.0.1 on 2022-05-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_user_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_gallery',
            old_name='id',
            new_name='unique_id',
        ),
    ]
