# Generated by Django 4.0.1 on 2022-05-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_rename_id_user_gallery_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
