# Generated by Django 4.0.1 on 2022-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_message',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('phonenumber', models.CharField(max_length=10, null=True, verbose_name='Mobile Number')),
                ('message', models.CharField(max_length=500, null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
